name: ames
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  flame: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  audioplayers: ^5.2.1
  torch_light: ^1.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/images/
